### ISSUE TITLE
Create DB Schema

### ISSUE THREAD

**Issue by Kropanov** [Egev604/appin2lemetry#20]
Use SQLiteStudio or SQLiteFlow or DBeaver (Open-source SQLite Database clients and managers)
When you create the Schema, simply attach screenshot to this issue to close this task.

main schema entities:
- user (id, firstName, lastName, password, email, access, ...)
- pc (id, name, assembled, ...)
- pc parts (id, name, ...)
...
add additional entities by linking tables:
user -> ps -> ps part ...

**Comment by Egev604** [comment]
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/e8db5a61-b887-4d86-81bc-6de1500f755f)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/10545309-429b-46c5-b1f7-fca80c51d4e0)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/76ab244b-65c2-4123-8d6b-6cea9e8a8bc5)

**Comment by Kropanov** [comment]
Not sure, please, update tables!

**Comment by Egev604** [comment]
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/4a972f4f-d98b-47db-a206-13d9eb5564c5)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/5e843d74-40af-493e-a3bc-418ec2cf5d43)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/ec7220ee-0e60-4059-8fde-68e06534056c)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/e48936c3-f336-41b8-b251-c6dc91c7cf6c)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/51e21822-0c18-4104-b6a8-f8066a26a363)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/1183c1c5-f979-4586-83df-0ddd2d737fed)

**Comment by Egev604** [comment]
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/fcb06fcc-2b76-428b-8e0c-ebe31c35f913)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/1cb735ee-6b2c-4ba9-9a71-09254d3cbcd4)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/2a69d325-5778-4ff8-8caa-6365a7f9a399)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/26c698bd-6313-46b2-a702-eef3cc6d47b6)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/67387254-a2bb-406b-b370-9c313f1a6386)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/dd986082-f0e2-4c32-b150-c742bb623a63)
![image](https://github.com/Egev604/appin2lemetry/assets/117158658/7b462f51-eb12-406b-87f7-cd8f71ee44ee)
